banner = [
    '<span class="index">ForrestKnight (FK) Not A Corporation. All knights reserved.</span>',
"                                                   ,: ",
"                                                 ,' | ",
"                                                /   : ",
"                                             --'   /  ",
"                                             \/ />/   ",
"                                             / /_\    ",
"                                          __/   /     ",
"                                          )'-. /      ",
"                                          ./  :\      ",
"                                           /.' '      ",
"                                         '/'          ",
"                                         +            ",
"                                        '             ",
"                                      `.              ",
"                                  .-/ )               ",
"                                 (    |               ",
"                              . .-'  '.               ",
"                             ( (.   )8:               ",
"                         .'    / (_  )                ",
"                          _. :(.   )8P  `             ",
"                      .  (  `-' (  `.   .             ",
"                       .  :  (   .a8a)                ",
"                      /_`( a `a. )'                    ________ __    __________   ",
"                  (  (/  .  ' )=='                    / /  _/ //_/   / /  _/  _/      ",
"                 (   (    )  .8   +              __  / // // ,< __  / // / / /       ",
"                   (`'8a.( _(   (              / /_/ // // /| / /_/ // /_/ /        ",
"                ..-. `8P    ) `  )  +          \____/___/_/ |_\____/___/___/        ",
"              -'   (      -ab:  )                     ",
"            '    _  `    (8PYa                        ",
"          _(    (    )b  -`.  ) +                     ",
"         ( 8)  ( _.aP _a   \( \   *                   ",
"       +  )/    (8P   (88    )  )                     ",
"          (a:f   |     (       /                      ",
    '<span class="color2">Welcome to my interactive web terminal.</span>',
    "<span class=\"color2\">For a list of available commands, type</span> <span class=\"command\">'help'</span><span class=\"color2\">.</span>",
];


                                







banner = [
    '<span class="index">ForrestKnight (FK) Not A Corporation. All knights reserved.</span>',

"                           *     .--.                  ",
"                                / /  `                 ",
"               +               | |                     ",
"                      '         \ \__,                 ",
"                  *          +   '--'  *               ",
"                      +   /\                           ",
"         +              .'  '.   *                     ",
"                *      /======\      +                 ",
"                      ;:.  _   ;                       ",
"                      |:. (_)  |                       ",
"                      |:.  _   |                       ",
"            +         |:. (_)  |          *                        ________ __    __________   ",
"                      ;:.      ;                                  / /  _/ //_/   / /  _/  _/   ",
"                    .' \:.    / `.                           __  / // // ,< __  / // / / /     ",
"                   / .-'':._.'`-. \                         / /_/ // // /| / /_/ // /_/ /      ",
"                   |/    /||\    \|                         \____/___/_/ |_\____/___/___/      ",
"                _..~~~~~~~~~~~~~~~~.._                                                          ",
"           _.-'``                    ``'-._                                                    ",
"         -'                                '-                                                  ",
"      ,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,.   ",
  "~~,;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;,~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    '<span class="color2">Welcome to my interactive web terminal.</span>',
    "<span class=\"color2\">For a list of available commands, type</span> <span class=\"command\">'help'</span><span class=\"color2\">.</span>",
];





banner = [
    '<span class="index">ForrestKnight (FK) Not A Corporation. All knights reserved.</span>',
"                                                   ,: ",
"                                                 ,' | ",
"                                                /   : ",
"                                             --'   /  ",
"                                             \/ />/   ",
"                                             / /_\    ",
"                                          __/   /     ",
"                                          )'-. /      ",
"                                          ./  :\      ",
"                                           /.' '      ",
"                                         '/'          ",
"                                         +            ",
"                                        '             ",
"                                      `.              ",
"                                  .-/ )               ",
"                                 (    |               ",
"                              . .-'  '.               ",
"                             ( (.   )8:               ",
"                         .'    / (_  )                ",
"                          _. :(.   )8P  `             ",
"                      .  (  `-' (  `.   .             ",
"                       .  :  (   .a8a)                ",
"                      /_`( a `a. )'                    ________ __    __________   ",
"                  (  (/  .  ' )=='                    / /  _/ //_/   / /  _/  _/      ",
"                 (   (    )  .8   +              __  / // // ,< __  / // / / /       ",
"                   (`'8a.( _(   (              / /_/ // // /| / /_/ // /_/ /        ",
"                ..-. `8P    ) `  )  +          \____/___/_/ |_\____/___/___/        ",
"              -'   (      -ab:  )                     ",
"            '    _  `    (8PYa                        ",
"          _(    (    )b  -`.  ) +                     ",
"         ( 8)  ( _.aP _a   \( \   *                   ",
"       +  )/    (8P   (88    )  )                     ",
"          (a:f   |     (       /                      ",
    '<span class="color2">Welcome to my interactive web terminal.</span>',
    "<span class=\"color2\">For a list of available commands, type</span> <span class=\"command\">'help'</span><span class=\"color2\">.</span>",
];